version: "3.7"
services:
  worker:
    image: elixir_swarm_worker:latest
    command: iex --sname app --cookie cookiemonster -S mix run start_workers.exs
    labels:
      - "libcluster_docker=true"
    deploy:
      replicas: 2
    networks:
      - libcluster_docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  libcluster_docker:
    external: true
    name: libcluster_docker
